[project]
name = "cdc-rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "langchain>=0.3.27",
    "pymupdf>=1.26.3",
    "python-dotenv>=1.1.1",
]
